export * as Global from './Global.mjs';
export * as BuildIn from './BuildIn.mjs';

export * as Array from './Array.mjs';
export * as ArrayBuffer from './ArrayBuffer.mjs';
export * as Atomics from './Atomics.mjs';
export * as BigInt from './BigInt.mjs';
export * as BigInt64Array from './BigInt64Array.mjs';
export * as BigUint64Array from './BigUint64Array.mjs';
export * as Date from './Date.mjs';
export * as Float32Array from './Float32Array.mjs';
export * as Float64Array from './Float64Array.mjs';
export * as Int8Array from './Int8Array.mjs';
export * as Int16Array from './Int16Array.mjs';
export * as Int32Array from './Int32Array.mjs';
export * as Intl from './Intl.mjs';
export * as JSON from './JSON.mjs';
export * as Map from './Map.mjs';
export * as Math from './Math.mjs';
export * as Number from './Number.js';
export * as Object from './Object.mjs';
export * as Promise from './Promise.mjs';
export * as Proxy from './Proxy.mjs';
export * as Reflect from './Reflect.mjs';
export * as String from './String.mjs';
export * as Symbol from './Symbol.mjs';
export * as Uint8Array from './Uint8Array.mjs';
export * as Uint8ClampedArray from './Uint8ClampedArray.mjs';
export * as Uint16Array from './Uint16Array.mjs';
export * as Uint32Array from './Uint32Array.mjs';

export * from './ES.mjs';
