import { GetterSetter } from './Generator.mjs';

export const abs = GetterSetter('abs');
export const acos = GetterSetter('acos');
export const acosh = GetterSetter('acosh');
export const add = GetterSetter('add');
export const all = GetterSetter('all');
export const allSettled = GetterSetter('allSettled');
export const and = GetterSetter('and');
export const any = GetterSetter('any');
export const apply = GetterSetter('apply');
export const asIntN = GetterSetter('asIntN');
export const asin = GetterSetter('asin');
export const asinh = GetterSetter('asinh');
export const assign = GetterSetter('assign');
export const asyncIterator = GetterSetter('asyncIterator');
export const at = GetterSetter('at');
export const atan = GetterSetter('atan');
export const atan2 = GetterSetter('atan2');
export const atanh = GetterSetter('atanh');
export const asUintN = GetterSetter('asUintN');

export const BYTES_PER_ELEMENT = GetterSetter('BYTES_PER_ELEMENT');
export const bind = GetterSetter('bind');
export const buffer = GetterSetter('buffer');
export const byteLength = GetterSetter('byteLength');
export const byteOffset = GetterSetter('byteOffset');

export const Collator = GetterSetter('Collator');
export const call = GetterSetter('call');
export const cause = GetterSetter('cause');
export const cbrt = GetterSetter('cbrt');
export const ceil = GetterSetter('ceil');
export const charAt = GetterSetter('charAt');
export const charCodeAt = GetterSetter('charCodeAt');
export const clear = GetterSetter('clear');
export const clz32 = GetterSetter('clz32');
export const codePointAt = GetterSetter('codePointAt');
export const compareExchange = GetterSetter('compareExchange');
export const concat = GetterSetter('concat');
export const construct = GetterSetter('construct');
export const constructor = GetterSetter('constructor');
export const copyWithin = GetterSetter('copyWithin');
export const cos = GetterSetter('cos');
export const cosh = GetterSetter('cosh');
export const create = GetterSetter('create');

export const DateTimeFormat = GetterSetter('DateTimeFormat');
export const defineProperties = GetterSetter('defineProperties');
export const defineProperty = GetterSetter('defineProperty');
export const deleteProperty = GetterSetter('deleteProperty');
export const deref = GetterSetter('deref');
export const detached = GetterSetter('detached');
export const difference = GetterSetter('difference');
export const dotAll = GetterSetter('dotAll');

export const E = GetterSetter('E');
export const EPSILON = GetterSetter('EPSILON');
export const endsWith = GetterSetter('endsWith');
export const entries = GetterSetter('entries');
export const errors = GetterSetter('errors');
export const every = GetterSetter('every');
export const exec = GetterSetter('exec');
export const exp = GetterSetter('exp');
export const expm1 = GetterSetter('expm1');

export const fill = GetterSetter('fill');
export const filter = GetterSetter('filter');
export const find = GetterSetter('find');
export const findIndex = GetterSetter('findIndex');
export const findLast = GetterSetter('findLast');
export const findLastIndex = GetterSetter('findLastIndex');
export const flags = GetterSetter('flags');
export const flat = GetterSetter('flat');
export const flatMap = GetterSetter('flatMap');
export const floor = GetterSetter('floor');
export const forEach = GetterSetter('forEach');
export const freeze = GetterSetter('freeze');
export const from = GetterSetter('from');
export const fromAsync = GetterSetter('fromAsync');
export const fromCharCode = GetterSetter('fromCharCode');
export const fromCodePoint = GetterSetter('fromCodePoint');
export const fromEntries = GetterSetter('fromEntries');
export const fround = GetterSetter('fround');

export const get = GetterSetter('get');
export const getBigInt64 = GetterSetter('getBigInt64');
export const getBigUint64 = GetterSetter('getBigUint64');
export const getCanonicalLocales = GetterSetter('getCanonicalLocales');
export const getDate = GetterSetter('getDate');
export const getDay = GetterSetter('getDate');
export const getFloat32 = GetterSetter('getFloat32');
export const getFloat64 = GetterSetter('getFloat64');
export const getFullYear = GetterSetter('getFullYear');
export const getHours = GetterSetter('getHours');
export const getInt16 = GetterSetter('getInt16');
export const getInt32 = GetterSetter('getInt32');
export const getInt8 = GetterSetter('getInt8');
export const getMilliseconds = GetterSetter('getMilliseconds');
export const getMinutes = GetterSetter('getMinutes');
export const getMonth = GetterSetter('getMonth');
export const getOwnPropertyDescriptor = GetterSetter('getOwnPropertyDescriptor');
export const getOwnPropertyDescriptors = GetterSetter('getOwnPropertyDescriptors');
export const getOwnPropertyNames = GetterSetter('getOwnPropertyNames');
export const getOwnPropertySymbols = GetterSetter('getOwnPropertySymbols');
export const getPrototypeOf = GetterSetter('getPrototypeOf');
export const getSeconds = GetterSetter('getSeconds');
export const getTime = GetterSetter('getTime');
export const getTimezoneOffset = GetterSetter('getTimezoneOffset');
export const getUint16 = GetterSetter('getUint16');
export const getUint32 = GetterSetter('getUint32');
export const getUint8 = GetterSetter('getUint8');
export const getUTCDate = GetterSetter('getUTCDate');
export const getUTCDay = GetterSetter('getUTCDay');
export const getUTCFullYear = GetterSetter('getUTCFullYear');
export const getUTCHours = GetterSetter('getUTCHours');
export const getUTCMilliseconds = GetterSetter('getUTCMilliseconds');
export const getUTCMinutes = GetterSetter('getUTCMinutes');
export const getUTCMonth = GetterSetter('getUTCMonth');
export const getUTCSeconds = GetterSetter('getUTCSeconds');
export const global = GetterSetter('global');
export const groupBy = GetterSetter('groupBy');
export const grow = GetterSetter('grow');
export const growable = GetterSetter('growable');

export const has = GetterSetter('has');
export const hasIndices = GetterSetter('hasIndices');
export const hasInstance = GetterSetter('hasInstance');
export const hasOwn = GetterSetter('hasOwn');
export const hasOwnProperty = GetterSetter('hasOwnProperty');
export const hypot = GetterSetter('hypot');

export const ignoreCase = GetterSetter('ignoreCase');
export const imul = GetterSetter('imul');
export const includes = GetterSetter('includes');
export const indexOf = GetterSetter('indexOf');
export const intersection = GetterSetter('intersection');
export const is = GetterSetter('is');
export const isArray = GetterSetter('isArray');
export const isConcatSpreadable = GetterSetter('isConcatSpreadable');
export const isDisjointFrom = GetterSetter('isDisjointFrom');
export const isExtensible = GetterSetter('isExtensible');
export const isFrozen = GetterSetter('isFrozen');
export const isInteger = GetterSetter('isInteger');
export const isLockFree = GetterSetter('isLockFree');
export const isPrototypeOf = GetterSetter('isPrototypeOf');
export const isSafeInteger = GetterSetter('isSafeInteger');
export const isSealed = GetterSetter('isSealed');
export const isSubsetOf = GetterSetter('isSubsetOf');
export const isSupersetOf = GetterSetter('isSupersetOf');
export const isView = GetterSetter('isView');
export const isWellFormed = GetterSetter('isWellFormed');
export const iterator = GetterSetter('iterator');

export const join = GetterSetter('join');

export const keyFor = GetterSetter('keyFor');
export const keys = GetterSetter('keys');

export const ListFormat = GetterSetter('ListFormat');
export const LN10 = GetterSetter('LN10');
export const LN2 = GetterSetter('LN2');
export const LOG10E = GetterSetter('LOG10E');
export const LOG2E = GetterSetter('LOG2E');
export const lastIndex = GetterSetter('lastIndex');
export const lastIndexOf = GetterSetter('lastIndexOf');
export const length = GetterSetter('length');
export const load = GetterSetter('load');
export const localeCompare = GetterSetter('localeCompare');
export const log = GetterSetter('log');
export const log10 = GetterSetter('log10');
export const log1p = GetterSetter('log1p');
export const log2 = GetterSetter('log2');

export const MAX_SAFE_INTEGER = GetterSetter('MAX_SAFE_INTEGER');
export const MAX_VALUE = GetterSetter('MAX_VALUE');
export const MIN_SAFE_INTEGER = GetterSetter('MIN_SAFE_INTEGER');
export const MIN_VALUE = GetterSetter('MIN_VALUE');
export const map = GetterSetter('map');
export const match = GetterSetter('match');
export const matchAll = GetterSetter('matchAll');
export const max = GetterSetter('max');
export const maxByteLength = GetterSetter('maxByteLength');
export const message = GetterSetter('message');
export const min = GetterSetter('min');
export const multiline = GetterSetter('multiline');

export const NEGATIVE_INFINITY = GetterSetter('NEGATIVE_INFINITY');
export const NumberFormat = GetterSetter('NumberFormat');
export const name = GetterSetter('name');
export const next = GetterSetter('next');
export const normalize = GetterSetter('normalize');
export const notify = GetterSetter('notify');
export const now = GetterSetter('now');

export const of = GetterSetter('of');
export const or = GetterSetter('or');
export const ownKeys = GetterSetter('ownKeys');

export const PI = GetterSetter('PI');
export const PluralRules = GetterSetter('PluralRules');
export const POSITIVE_INFINITY = GetterSetter('POSITIVE_INFINITY');
export const padEnd = GetterSetter('padEnd');
export const padStart = GetterSetter('padStart');
export const parse = GetterSetter('parse');
export const pop = GetterSetter('pop');
export const pow = GetterSetter('pow');
export const preventExtensions = GetterSetter('preventExtensions');
export const propertyIsEnumerable = GetterSetter('propertyIsEnumerable');
export const prototype = GetterSetter('prototype');
export const push = GetterSetter('push');

export const RelativeTimeFormat = GetterSetter('RelativeTimeFormat');
export const race = GetterSetter('race');
export const random = GetterSetter('random');
export const raw = GetterSetter('raw');
export const reduce = GetterSetter('reduce');
export const reduceRight = GetterSetter('reduceRight');
export const register = GetterSetter('register');
export const reject = GetterSetter('reject');
export const repeat = GetterSetter('repeat');
export const replace = GetterSetter('replace');
export const replaceAll = GetterSetter('replaceAll');
export const reserve = GetterSetter('reserve');
export const resizable = GetterSetter('resizable');
export const resize = GetterSetter('resize');
export const resolve = GetterSetter('resolve');
export const revocable = GetterSetter('revocable');
export const round = GetterSetter('round');

export const SQRT1_2 = GetterSetter('SQRT1_2');
export const SQRT2 = GetterSetter('SQRT2');
export const Segmenter = GetterSetter('Segmenter');
export const seal = GetterSetter('seal');
export const search = GetterSetter('search');
export const set = GetterSetter('set');
export const setBigInt64 = GetterSetter('setBigInt64');
export const setBigUint64 = GetterSetter('setBigUint64');
export const setDate = GetterSetter('setDate');
export const setFloat32 = GetterSetter('setFloat32');
export const setFloat64 = GetterSetter('setFloat64');
export const setFullYear = GetterSetter('setFullYear');
export const setHours = GetterSetter('setHours');
export const setInt16 = GetterSetter('setInt16');
export const setInt32 = GetterSetter('setInt32');
export const setInt8 = GetterSetter('setInt8');
export const setMilliseconds = GetterSetter('setMilliseconds');
export const setMinutes = GetterSetter('setMinutes');
export const setMonth = GetterSetter('setMonth');
export const setPrototypeOf = GetterSetter('setPrototypeOf');
export const setSeconds = GetterSetter('setSeconds');
export const setTime = GetterSetter('setTime');
export const setUint16 = GetterSetter('setUint16');
export const setUint32 = GetterSetter('setUint32');
export const setUint8 = GetterSetter('setUint8');
export const setUTCDate = GetterSetter('setUTCDate');
export const setUTCFullYear = GetterSetter('setUTCFullYear');
export const setUTCHours = GetterSetter('setUTCHours');
export const setUTCMilliseconds = GetterSetter('setUTCMilliseconds');
export const setUTCMinutes = GetterSetter('setUTCMinutes');
export const setUTCMonth = GetterSetter('setUTCMonth');
export const setUTCSeconds = GetterSetter('setUTCSeconds');
export const shift = GetterSetter('shift');
export const sign = GetterSetter('sign');
export const sin = GetterSetter('sin');
export const sinh = GetterSetter('sinh');
export const size = GetterSetter('size');
export const slice = GetterSetter('slice');
export const some = GetterSetter('some');
export const sort = GetterSetter('sort');
export const source = GetterSetter('source');
export const splice = GetterSetter('splice');
export const split = GetterSetter('split');
export const species = GetterSetter('species');
export const sqrt = GetterSetter('sqrt');
export const startsWith = GetterSetter('startsWith');
export const sticky = GetterSetter('sticky');
export const store = GetterSetter('store');
export const stringify = GetterSetter('stringify');
export const sub = GetterSetter('sub');
export const subarray = GetterSetter('subarray');
export const substring = GetterSetter('substring');
export const supportedValuesOf = GetterSetter('supportedValuesOf');
export const symmetricDifference = GetterSetter('symmetricDifference');

export const tan = GetterSetter('tan');
export const tanh = GetterSetter('tanh');
export const test = GetterSetter('test');
export const then = GetterSetter('then');
export const toDateString = GetterSetter('toDateString');
export const toExponential = GetterSetter('toExponential');
export const toFixed = GetterSetter('toFixed');
export const toISOString = GetterSetter('toISOString');
export const toLocaleDateString = GetterSetter('toLocaleDateString');
export const toLocaleLowerCase = GetterSetter('toLocaleLowerCase');
export const toLocaleUpperCase = GetterSetter('toLocaleUpperCase');
export const toLocaleString = GetterSetter('toLocaleString');
export const toLocaleTimeString = GetterSetter('toLocaleTimeString');
export const toLowerCase = GetterSetter('toLowerCase');
export const toPrecision = GetterSetter('toPrecision');
export const toPrimitive = GetterSetter('toPrimitive');
export const toReversed = GetterSetter('toReversed');
export const toSorted = GetterSetter('toSorted');
export const toSpliced = GetterSetter('toSpliced');
export const toString = GetterSetter('toString');
export const toStringTag = GetterSetter('toStringTag');
export const toTimeString = GetterSetter('toTimeString');
export const toUpperCase = GetterSetter('toUpperCase');
export const toUTCString = GetterSetter('toUTCString');
export const toWellFormed = GetterSetter('toWellFormed');
export const transfer = GetterSetter('transfer');
export const transferToFixedLength = GetterSetter('transferToFixedLength');
export const trim = GetterSetter('trim');
export const trimEnd = GetterSetter('trimEnd');
export const trimStart = GetterSetter('trimStart');
export const trunc = GetterSetter('trunc');

export const UTC = GetterSetter('UTC');
export const unicode = GetterSetter('unicode');
export const unicodeSets = GetterSetter('unicodeSets');
export const union = GetterSetter('union');
export const unregister = GetterSetter('unregister');
export const unscopables = GetterSetter('unscopables');
export const unshift = GetterSetter('unshift');

export const valueOf = GetterSetter('valueOf');
export const values = GetterSetter('values');

export const wait = GetterSetter('wait');
export const waitAsync = GetterSetter('waitAsync');
export const withResolvers = GetterSetter('withResolvers');

export const xor = GetterSetter('xor');

// reserved words
const _catch = GetterSetter('catch');
const _delete = GetterSetter('delete');
const _finally = GetterSetter('finally');
const _for = GetterSetter('for');
const _return = GetterSetter('return');
const _throw = GetterSetter('throw');
const _with = GetterSetter('with');

export {
	_catch as catch,
	_delete as delete,
	_finally as finally,
	_for as for,
	_return as return,
	_throw as throw,
	_with as with,
};
