type Caller<T = any> = (o: T, ...args: any) => any;
type Getter = <T extends object>(o: T) => T[keyof T];
type GetterSetter = <T extends object>(o: T, value?: any) => T[keyof T];
type Constructor = abstract new (...args: any) => any;

export function Bind<T>(target: T, caller: Caller): Caller;

export module Generator {
	export function Getter(key: string): Getter;
	export function Caller(key: string): Caller;
	export function GetterCaller(getter: Getter): Caller;

	export function Constructor<T extends Constructor>(
		Target: T
	): (...args: ConstructorParameters<T>) => InstanceType<T>;

	export function GetterSetter(key: string): GetterSetter;
}

export module Getter {
	export const abs: Getter;
	export const acos: Getter;
	export const acosh: Getter;
	export const add: Getter;
	export const all: Getter;
	export const allSettled: Getter;
	export const and: Getter;
	export const any: Getter;
	export const apply: Getter;
	export const asIntN: Getter;
	export const asin: Getter;
	export const asinh: Getter;
	export const assign: Getter;
	export const asyncIterator: Getter;
	export const at: Getter;
	export const atan: Getter;
	export const atan2: Getter;
	export const atanh: Getter;
	export const asUintN: Getter;
	export const BYTES_PER_ELEMENT: Getter;
	export const bind: Getter;
	export const buffer: Getter;
	export const byteLength: Getter;
	export const byteOffset: Getter;
	export const Collator: Getter;
	export const call: Getter;
	export const cbrt: Getter;
	export const ceil: Getter;
	export const charAt: Getter;
	export const charCodeAt: Getter;
	export const clear: Getter;
	export const clz32: Getter;
	export const codePointAt: Getter;
	export const compareExchange: Getter;
	export const concat: Getter;
	export const construct: Getter;
	export const constructor: Getter;
	export const copyWithin: Getter;
	export const cos: Getter;
	export const cosh: Getter;
	export const create: Getter;
	export const DateTimeFormat: Getter;
	export const defineProperties: Getter;
	export const defineProperty: Getter;
	export const deleteProperty: Getter;
	export const deref: Getter;
	export const detached: Getter;
	export const difference: Getter;
	export const dotAll: Getter;
	export const E: Getter;
	export const EPSILON: Getter;
	export const endsWith: Getter;
	export const entries: Getter;
	export const every: Getter;
	export const exec: Getter;
	export const exp: Getter;
	export const expm1: Getter;
	export const fill: Getter;
	export const filter: Getter;
	export const find: Getter;
	export const findIndex: Getter;
	export const findLast: Getter;
	export const findLastIndex: Getter;
	export const flags: Getter;
	export const flat: Getter;
	export const flatMap: Getter;
	export const floor: Getter;
	export const forEach: Getter;
	export const freeze: Getter;
	export const from: Getter;
	export const fromAsync: Getter;
	export const fromCharCode: Getter;
	export const fromCodePoint: Getter;
	export const fromEntries: Getter;
	export const fround: Getter;
	export const get: Getter;
	export const getBigInt64: Getter;
	export const getBigUint64: Getter;
	export const getCanonicalLocales: Getter;
	export const getDate: Getter;
	export const getDay: Getter;
	export const getFloat32: Getter;
	export const getFloat64: Getter;
	export const getFullYear: Getter;
	export const getHours: Getter;
	export const getInt16: Getter;
	export const getInt32: Getter;
	export const getInt8: Getter;
	export const getMilliseconds: Getter;
	export const getMinutes: Getter;
	export const getMonth: Getter;
	export const getOwnPropertyDescriptor: Getter;
	export const getOwnPropertyDescriptors: Getter;
	export const getOwnPropertyNames: Getter;
	export const getOwnPropertySymbols: Getter;
	export const getPrototypeOf: Getter;
	export const getSeconds: Getter;
	export const getTime: Getter;
	export const getTimezoneOffset: Getter;
	export const getUint16: Getter;
	export const getUint32: Getter;
	export const getUint8: Getter;
	export const getUTCDate: Getter;
	export const getUTCDay: Getter;
	export const getUTCFullYear: Getter;
	export const getUTCHours: Getter;
	export const getUTCMilliseconds: Getter;
	export const getUTCMinutes: Getter;
	export const getUTCMonth: Getter;
	export const getUTCSeconds: Getter;
	export const global: Getter;
	export const groupBy: Getter;
	export const grow: Getter;
	export const growable: Getter;
	export const has: Getter;
	export const hasIndices: Getter;
	export const hasInstance: Getter;
	export const hasOwn: Getter;
	export const hasOwnProperty: Getter;
	export const hypot: Getter;
	export const ignoreCase: Getter;
	export const imul: Getter;
	export const includes: Getter;
	export const indexOf: Getter;
	export const intersection: Getter;
	export const is: Getter;
	export const isArray: Getter;
	export const isConcatSpreadable: Getter;
	export const isDisjointFrom: Getter;
	export const isExtensible: Getter;
	export const isFrozen: Getter;
	export const isInteger: Getter;
	export const isLockFree: Getter;
	export const isPrototypeOf: Getter;
	export const isSafeInteger: Getter;
	export const isSealed: Getter;
	export const isSubsetOf: Getter;
	export const isSupersetOf: Getter;
	export const isView: Getter;
	export const isWellFormed: Getter;
	export const iterator: Getter;
	export const join: Getter;
	export const keyFor: Getter;
	export const keys: Getter;
	export const ListFormat: Getter;
	export const LN10: Getter;
	export const LN2: Getter;
	export const LOG10E: Getter;
	export const LOG2E: Getter;
	export const lastIndex: Getter;
	export const lastIndexOf: Getter;
	export const length: Getter;
	export const load: Getter;
	export const localeCompare: Getter;
	export const log: Getter;
	export const log10: Getter;
	export const log1p: Getter;
	export const log2: Getter;
	export const MAX_SAFE_INTEGER: Getter;
	export const MAX_VALUE: Getter;
	export const MIN_SAFE_INTEGER: Getter;
	export const MIN_VALUE: Getter;
	export const map: Getter;
	export const match: Getter;
	export const matchAll: Getter;
	export const max: Getter;
	export const maxByteLength: Getter;
	export const min: Getter;
	export const multiline: Getter;
	export const NEGATIVE_INFINITY: Getter;
	export const NumberFormat: Getter;
	export const name: Getter;
	export const next: Getter;
	export const normalize: Getter;
	export const notify: Getter;
	export const now: Getter;
	export const of: Getter;
	export const or: Getter;
	export const ownKeys: Getter;
	export const PI: Getter;
	export const PluralRules: Getter;
	export const POSITIVE_INFINITY: Getter;
	export const padEnd: Getter;
	export const padStart: Getter;
	export const parse: Getter;
	export const pop: Getter;
	export const pow: Getter;
	export const preventExtensions: Getter;
	export const propertyIsEnumerable: Getter;
	export const prototype: Getter;
	export const push: Getter;
	export const RelativeTimeFormat: Getter;
	export const race: Getter;
	export const random: Getter;
	export const raw: Getter;
	export const reduce: Getter;
	export const reduceRight: Getter;
	export const register: Getter;
	export const reject: Getter;
	export const repeat: Getter;
	export const replace: Getter;
	export const replaceAll: Getter;
	export const reserve: Getter;
	export const resizable: Getter;
	export const resize: Getter;
	export const resolve: Getter;
	export const revocable: Getter;
	export const round: Getter;
	export const SQRT1_2: Getter;
	export const SQRT2: Getter;
	export const Segmenter: Getter;
	export const seal: Getter;
	export const search: Getter;
	export const set: Getter;
	export const setBigInt64: Getter;
	export const setBigUint64: Getter;
	export const setDate: Getter;
	export const setFloat32: Getter;
	export const setFloat64: Getter;
	export const setFullYear: Getter;
	export const setHours: Getter;
	export const setInt16: Getter;
	export const setInt32: Getter;
	export const setInt8: Getter;
	export const setMilliseconds: Getter;
	export const setMinutes: Getter;
	export const setMonth: Getter;
	export const setPrototypeOf: Getter;
	export const setSeconds: Getter;
	export const setTime: Getter;
	export const setUint16: Getter;
	export const setUint32: Getter;
	export const setUint8: Getter;
	export const setUTCDate: Getter;
	export const setUTCFullYear: Getter;
	export const setUTCHours: Getter;
	export const setUTCMilliseconds: Getter;
	export const setUTCMinutes: Getter;
	export const setUTCMonth: Getter;
	export const setUTCSeconds: Getter;
	export const shift: Getter;
	export const sign: Getter;
	export const sin: Getter;
	export const sinh: Getter;
	export const size: Getter;
	export const slice: Getter;
	export const some: Getter;
	export const sort: Getter;
	export const source: Getter;
	export const splice: Getter;
	export const split: Getter;
	export const species: Getter;
	export const sqrt: Getter;
	export const startsWith: Getter;
	export const sticky: Getter;
	export const store: Getter;
	export const stringify: Getter;
	export const sub: Getter;
	export const subarray: Getter;
	export const substring: Getter;
	export const supportedValuesOf: Getter;
	export const symmetricDifference: Getter;
	export const tan: Getter;
	export const tanh: Getter;
	export const test: Getter;
	export const then: Getter;
	export const toDateString: Getter;
	export const toExponential: Getter;
	export const toFixed: Getter;
	export const toISOString: Getter;
	export const toLocaleDateString: Getter;
	export const toLocaleLowerCase: Getter;
	export const toLocaleUpperCase: Getter;
	export const toLocaleString: Getter;
	export const toLocaleTimeString: Getter;
	export const toLowerCase: Getter;
	export const toPrecision: Getter;
	export const toPrimitive: Getter;
	export const toReversed: Getter;
	export const toSorted: Getter;
	export const toSpliced: Getter;
	export const toString: Getter;
	export const toStringTag: Getter;
	export const toTimeString: Getter;
	export const toUpperCase: Getter;
	export const toUTCString: Getter;
	export const toWellFormed: Getter;
	export const transfer: Getter;
	export const transferToFixedLength: Getter;
	export const trim: Getter;
	export const trimEnd: Getter;
	export const trimStart: Getter;
	export const trunc: Getter;
	export const UTC: Getter;
	export const unicode: Getter;
	export const unicodeSets: Getter;
	export const union: Getter;
	export const unregister: Getter;
	export const unscopables: Getter;
	export const unshift: Getter;
	export const valueOf: Getter;
	export const values: Getter;
	export const wait: Getter;
	export const waitAsync: Getter;
	export const withResolvers: Getter;
	export const xor: Getter;

	const _catch: Getter;
	const _delete: Getter;
	const _finally: Getter;
	const _for: Getter;
	const _return: Getter;
	const _throw: Getter;
	const _with: Getter;

	export {
		_catch as catch,
		_delete as delete,
		_finally as finally,
		_for as for,
		_return as return,
		_throw as throw,
		_with as with,
	}
}

export module GetterSetter {
	export const errors: GetterSetter;
	export const length: GetterSetter;
	export const name: GetterSetter;
	export const cause: GetterSetter;
	export const message: GetterSetter;
}

export module Caller {
	export const add: Caller;
	export const apply: Caller;
	export const at: Caller;
	export const bind: Caller;
	export const call: Caller;
	export const concat: Caller;
	export const copyWithin: Caller;
	export const from: Caller;
	export const of: Caller;
	export const has: Caller;
	export const hasOwnProperty: Caller;
	export const isPrototypeOf: Caller;
	export const propertyIsEnumerable: Caller;
	export const toLocalString: Caller;
	export const toString: Caller;
	export const valueOf: Caller;
	export const entries: Caller;
	export const every: Caller;
	export const fill: Caller;
	export const filter: Caller;
	export const find: Caller;
	export const findIndex: Caller;
	export const findLast: Caller;
	export const findLastIndex: Caller;
	export const flat: Caller;
	export const flatMap: Caller;
	export const floor: Caller;
	export const forEach: Caller;
	export const includes: Caller;
	export const indexOf: Caller;
	export const join: Caller;
	export const lastIndexOf: Caller;
	export const map: Caller;
	export const pop: Caller;
	export const push: Caller;
	export const reduce: Caller;
	export const reduceRight: Caller;
	export const reserve: Caller;
	export const shift: Caller;
	export const slice: Caller;
	export const some: Caller;
	export const sort: Caller;
	export const splice: Caller;
	export const toReversed: Caller;
	export const toSorted: Caller;
	export const toSpliced: Caller;
	export const unshift: Caller;
	export const values: Caller;
	export const resize: Caller;
	export const transfer: Caller;
	export const transferToFixedLength: Caller;
	export const next: Caller;
	export const keys: Caller;
	export const set: Caller;
	export const subarray: Caller;
	export const getBigInt64: Caller;
	export const getBigUint64: Caller;
	export const getFloat32: Caller;
	export const getFloat64: Caller;
	export const getInt16: Caller;
	export const getInt32: Caller;
	export const getInt8: Caller;
	export const getUint16: Caller;
	export const getUint32: Caller;
	export const getUint8: Caller;
	export const setBigInt64: Caller;
	export const setBigUint64: Caller;
	export const setFloat32: Caller;
	export const setFloat64: Caller;
	export const setInt16: Caller;
	export const setInt32: Caller;
	export const setInt8: Caller;
	export const setUint16: Caller;
	export const setUint32: Caller;
	export const setUint8: Caller;
	export const getDate: Caller;
	export const getDay: Caller;
	export const getFullYear: Caller;
	export const getHours: Caller;
	export const getMilliseconds: Caller;
	export const getMinutes: Caller;
	export const getMonth: Caller;
	export const getSeconds: Caller;
	export const getTime: Caller;
	export const getTimezoneOffset: Caller;
	export const getUTCDate: Caller;
	export const getUTCDay: Caller;
	export const getUTCFullYear: Caller;
	export const getUTCHours: Caller;
	export const getUTCMilliseconds: Caller;
	export const getUTCMinutes: Caller;
	export const getUTCMonth: Caller;
	export const getUTCSeconds: Caller;
	export const setDate: Caller;
	export const setFullYear: Caller;
	export const setHours: Caller;
	export const setMilliseconds: Caller;
	export const setMinutes: Caller;
	export const setMonth: Caller;
	export const setSeconds: Caller;
	export const setTime: Caller;
	export const setUTCDate: Caller;
	export const setUTCFullYear: Caller;
	export const setUTCHours: Caller;
	export const setUTCMilliseconds: Caller;
	export const setUTCMinutes: Caller;
	export const setUTCMonth: Caller;
	export const setUTCSeconds: Caller;
	export const toDateString: Caller;
	export const toISOString: Caller;
	export const toLocaleDateString: Caller;
	export const toLocaleTimeString: Caller;
	export const toTimeString: Caller;
	export const toUTCString: Caller;
	export const toExponential: Caller;
	export const toFixed: Caller;
	export const toPrecision: Caller;
	export const register: Caller;
	export const unregister: Caller;
	export const clear: Caller;
	export const get: Caller;
	export const then: Caller;
	export const exec: Caller;
	export const test: Caller;
	export const difference: Caller;
	export const intersection: Caller;
	export const isDisjointFrom: Caller;
	export const isSubsetOf: Caller;
	export const isSupersetOf: Caller;
	export const symmetricDifference: Caller;
	export const union: Caller;
	export const grow: Caller;
	export const charAt: Caller;
	export const charCodeAt: Caller;
	export const codePointAt: Caller;
	export const endsWith: Caller;
	export const isWellFormed: Caller;
	export const localeCompare: Caller;
	export const match: Caller;
	export const matchAll: Caller;
	export const normalize: Caller;
	export const padEnd: Caller;
	export const padStart: Caller;
	export const repeat: Caller;
	export const replace: Caller;
	export const replaceAll: Caller;
	export const search: Caller;
	export const split: Caller;
	export const startsWith: Caller;
	export const substring: Caller;
	export const toLocaleLowerCase: Caller;
	export const toLocaleUpperCase: Caller;
	export const toLowerCase: Caller;
	export const toUpperCase: Caller;
	export const toWellFormed: Caller;
	export const trim: Caller;
	export const trimEnd: Caller;
	export const trimStart: Caller;
	export const deref: Caller;

	const _catch: Caller;
	const _delete: Caller;
	const _finally: Caller;
	const _return: Caller;
	const _throw: Caller;
	const _with: Caller;

	export {
		_catch as catch,
		_delete as delete,
		_finally as finally,
		_return as return,
		_throw as throw,
		_with as with,
	}
}
